
?expr: expr "+" term -> add
     | expr "-" term -> sub
     | expr "true"
     | expr "false"
     | term
     | NUMBER
     | NAME

?term: term "*" atom -> mul
     | term "/" atom -> div
     | term "%%" atom -> mod
     | term "==" atom -> eq
     | term "!=" atom -> ineq
     | term "++" atom -> inc
     | term "--" atom -> dec
     | term "**" | "^" -> expo 
     | atom

?atom: NUMBER
     | "(" expr ")"

?print_stmt: "console.log" "(" expr ")"
?control_stmt: do_until
             | do_when
             | do_process

?do_until: "do" block "until" expr
block: "{" stmt* "}"
stmt: control_stmt 
    | print_stmt
    | expr
    | decl
    | assign
    | enum

?do_when: "do" block "when" expr
?do_process: "do" block

decl: "const" NAME "=" expr -> const_decl
assign: "let" NAME "=" expr -> var


start: stmt*


%import common.NUMBER
%import common.CNAME -> NAME
%import common.WS
%ignore WS




