
?expr: expr "+" term -> add
     | expr "-" term -> sub
     | term
     | NUMBER
     | NAME

?term: term "*" atom -> mul
     | term "/" atom -> div
     | term "%%" atom -> mod
     | term "==" atom -> eq
     | term "!=" atom -> ineq
     | term "++" atom -> inc
     | term "--" atom -> dec
     | term "**" | "^" -> expo 
     | atom

?atom: NUMBER
     | "(" expr ")"

?print_stmt: "console.log" "(" expr ")"
?control_stmt: do_until
             | do_when
             | do_process

?do_until: "do" block "until" expr
block: "{" stmt* "}"
stmt: control_stmt 
    | print_stmt
    | expr
    | decl
    | assign
    | enum

?do_when: "do" block "when" expr
?do_process: "do" block

decl: "const" NAME ( "=" | "is" )expr -> const_var
assign: "let" NAME ( "=" | "is" ) expr -> var

ops: "is" NAME TYPE expr -> check_true
   | "isnt" NAME TYPE expr -> check_false
   | expr "||" expr -> or_op
   | expr "|||" expr -> and_op

comment: "//" /[^\n]/*
comments: "/*" /(.|\n)*?/ "*/"

types: NAME -> str
     | NUMBER -> num
bool: "false" | "true"

start: stmt*

%ignore comment
%ignore comments
%import common.NUMBER
%import common.CNAME -> NAME
%import common.WS
%ignore WS




